### PR TITLE
don't check signature if key is empty (closes #138)

### LINKED ISSUE #138: Kernel should not check signatures when key is empty
R output:

```
> IRkernel::main()
$version
[1] 5

$key
[1] ""

$signature_scheme
[1] "hmac-sha256"

$transport
[1] "tcp"

$ip
[1] "127.0.0.1"

$hb_port
[1] 57278

$control_port
[1] 57279

$shell_port
[1] 57280

$stdin_port
[1] 57281

$iopub_port
[1] 57282

Error: identical(signature, expected_signature) is not TRUE
Execution halted
```

The config file it was given is 

```json
{
  "version":5,
  "key":"",
  "signature_scheme":"hmac-sha256",
  "transport":"tcp",
  "ip":"127.0.0.1",
  "hb_port":57278,
  "control_port":57279,
  "shell_port":57280,
  "stdin_port":57281,
  "iopub_port":57282
}
```

### PR DESCRIPTION
**Pull request by willwhitney**

### CODE REVIEW

File: R/kernel.r [hunk 1]
```diff
@@ -30,7 +30,11 @@ wire_to_msg = function(parts) {
     }
     signature <- rawToChar(parts[[i + 1]])
     expected_signature <- sign_msg(parts[(i + 2):(i + 5)])
-    stopifnot(identical(signature, expected_signature))
+    if (!identical(connection_info$key, "")) {
+        signature <- rawToChar(parts[[i + 1]])
+        expected_signature <- sign_msg(parts[(i + 2):(i + 5)])
```
Comment (rgbkrk) [inline R/kernel.r]: Looks like `signature` and `expected_signature` are defined twice here.

**Comment by willwhitney** [comment]
Whoops, fixed it.

**Comment by takluyver** [comment]
Looks good, thanks
